spring.application.name=hotelbooking
spring.data.mongodb.uri=mongodb://localhost:27017/hotelbooking
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
app.frontend-url=http://localhost:5173
app.mail.from=no-reply@hotelbooking.local
spring.mail.host=
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
